# Generated by Django 5.2.6 on 2025-12-08 07:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elective', models.CharField(choices=[('MobileDev', 'Mobile Development'), ('ITBA', 'IT Business Analytics'), ('MMGD', 'Multimedia & Game Development')], max_length=50)),
                ('activity_name', models.CharField(max_length=100)),
                ('completion_time', models.DurationField()),
                ('completed', models.BooleanField(default=False)),
                ('engagement_score', models.FloatField(default=0)),
                ('total_interactions', models.IntegerField(default=0)),
                ('interaction_rate', models.FloatField(default=0)),
                ('time_efficiency', models.FloatField(default=0)),
                ('quality_indicators', models.JSONField(blank=True, default=dict)),
                ('attempts', models.IntegerField(default=1)),
                ('first_attempt_time', models.DurationField(blank=True, null=True)),
                ('last_attempt_time', models.DurationField(blank=True, null=True)),
                ('improvement_rate', models.FloatField(default=0)),
                ('date_completed', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'survey_activityresult',
                'ordering': ['-date_completed'],
                'unique_together': {('user', 'elective', 'activity_name')},
            },
        ),
    ]
