# Generated by Django 5.2.6 on 2025-12-08 18:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectiveRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey_scores', models.JSONField()),
                ('survey_weight', models.FloatField(default=0.6)),
                ('activity_scores', models.JSONField()),
                ('activity_weight', models.FloatField(default=0.4)),
                ('final_scores', models.JSONField()),
                ('recommended_elective', models.CharField(max_length=50)),
                ('confidence_score', models.FloatField()),
                ('date_generated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='combined_recommendation', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
