# Generated by Django 5.2.6 on 2025-11-26 01:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_elective', models.CharField(max_length=50)),
                ('trait_scores', models.JSONField()),
                ('elective_scores', models.JSONField()),
                ('date_completed', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='survey_result', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
