# Generated by Django 5.2.6 on 2025-11-26 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyresult',
            name='completion_time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='surveyresult',
            name='level',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='surveyresult',
            name='questions_answered',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='surveyresult',
            name='total_xp',
            field=models.IntegerField(default=0),
        ),
    ]
