# Generated by Django 5.2.6 on 2025-11-26 06:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_surveyresult_completion_time_surveyresult_level_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectiveRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey_scores', models.JSONField()),
                ('survey_weight', models.FloatField(default=0.6)),
                ('activity_scores', models.JSONField()),
                ('activity_weight', models.FloatField(default=0.4)),
                ('final_scores', models.JSONField()),
                ('recommended_elective', models.CharField(max_length=50)),
                ('confidence_score', models.FloatField()),
                ('date_generated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ActivityResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elective', models.CharField(choices=[('MobileDev', 'Mobile Development'), ('ITBA', 'IT Business Analytics'), ('MMGD', 'Multimedia & Game Development')], max_length=50)),
                ('activity_name', models.CharField(max_length=100)),
                ('completion_time', models.DurationField()),
                ('completed', models.BooleanField(default=False)),
                ('engagement_score', models.FloatField(default=0)),
                ('date_completed', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'elective', 'activity_name')},
            },
        ),
    ]
