# Generated by Django 5.2.6 on 2025-11-28 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_electiverecommendation_activityresult'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activityresult',
            options={'ordering': ['-date_completed']},
        ),
        migrations.AddField(
            model_name='activityresult',
            name='attempts',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='activityresult',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='activityresult',
            name='first_attempt_time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activityresult',
            name='improvement_rate',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='activityresult',
            name='interaction_rate',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='activityresult',
            name='last_attempt_time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activityresult',
            name='quality_indicators',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='activityresult',
            name='time_efficiency',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='activityresult',
            name='total_interactions',
            field=models.IntegerField(default=0),
        ),
    ]
