# Generated by Django 5.2.6 on 2025-12-08 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_alter_activityresult_options_activityresult_attempts_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActivityResult',
        ),
    ]
